export const SAVE_NOTE = 'SAVE_NOTE';
export const GET_NOTES = 'GET_NOTES';
export const DELETE_NOTE = 'DELETE_NOTE';
export const RESET_FORM = 'RESET_FORM';
export const CHANGE_CONTENT_FORM = 'CHANGE_CONTENT_FORM';
export const CHANGE_TITLE_FORM = 'CHANGE_TITLE_FORM';
export const UPDATE_DATA_FORM = 'UPDATE_DATA_FORM';
